browserName=chrome
url=https://crm.anhtester.com/admin/authentication
email=admin@example.com
password=123456
headless=false -- Set to true to run tests in headless mode
implicitWait=10
pageLoadTimeout=30
explicitWait=20
screenshotPath=./screenshots/
logLevel=INFO
databaseUrl=jdbc:mysql://localhost:3306/crm_test
SCREENSHOT_PATH= ./reports/screenshots/
RECORDVIDEO_PATH= ./reports/videos/
